package com.parkingApi.demo.repositories;

import com.parkingApi.demo.models.tbCar;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 25/04/2021
*/
@Repository
public interface tbCarRepository extends JpaRepository<tbCar, Integer>, JpaSpecificationExecutor<tbCar>  {
	@Query(value = "from tbCar t where ParkTime >= :parkDate AND OutTime is null")
	public List<tbCar> getAllParkedSince(@Param("parkDate")Date parkDate);
}
