package com.parkingApi.demo.repositories;

import com.parkingApi.demo.models.tbParkingLot;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
 
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 25/04/2021
*/
@Repository
public interface tbParkingLotRepository extends JpaRepository<tbParkingLot, Integer>, JpaSpecificationExecutor<tbParkingLot>  {

	 Optional<tbParkingLot> findByCarId(int carId);
	
}
