package com.parkingApi.demo.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.parkingApi.demo.models.tbParkingFee;

/**
* Generated by Spring Data Generator on 25/04/2021
*/
@Repository
public interface tbParkingFeeRepository extends JpaRepository<tbParkingFee, Integer>, JpaSpecificationExecutor<tbParkingFee>  {

}
